services:
  web:
    build: .
    restart: unless-stopped
    container_name: stricktly-coffee
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stricktly-coffee.rule=Host(`stricktlycoffee.be`) || Host(`www.stricktlycoffee.be`)"
      - "traefik.http.routers.stricktly-coffee.entrypoints=websecure"
      - "traefik.http.routers.stricktly-coffee.tls.certresolver=letsencrypt"
      - "traefik.http.services.stricktly-coffee.loadbalancer.server.port=80"
      - "traefik.http.routers.stricktly-coffee-http.rule=Host(`stricktlycoffee.be`) || Host(`www.stricktlycoffee.be`)"
      - "traefik.http.routers.stricktly-coffee-http.entrypoints=web"
      - "traefik.http.routers.stricktly-coffee-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
